import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { GitBranch, Loader2 } from "lucide-react";
import { fetchSnapshot } from "../services/share.js";
import ScoreDonut from "../components/ScoreDonut.jsx";

export default function PublicShare() {
  const { slug } = useParams();
  const [snapshot, setSnapshot] = useState(null);
  const [error, setError] = useState("");

  useEffect(() => {
    fetchSnapshot(slug)
      .then((row) => setSnapshot(row))
      .catch((err) => setError(err.message));
  }, [slug]);

  if (error) {
    return (
      <div className="min-h-screen bg-bg text-ink flex items-center justify-center px-6">
        <p className="text-sm text-flag">{error}</p>
      </div>
    );
  }

  if (!snapshot) {
    return (
      <div className="min-h-screen bg-bg text-ink flex items-center justify-center">
        <Loader2 size={20} className="animate-spin text-ink-faint" />
      </div>
    );
  }

  const { portfolioResult, repos, username } = snapshot.data;

  return (
    <div className="min-h-screen bg-bg text-ink">
      <header className="max-w-3xl mx-auto px-6 h-20 flex items-center justify-between">
        <Link
          to="/"
          className="flex items-center gap-2 font-display font-semibold text-lg"
        >
          <span className="w-7 h-7 rounded-lg bg-gradient-to-br from-violet to-cyan flex items-center justify-center">
            <GitBranch size={15} strokeWidth={2.5} />
          </span>
          DevTrack
        </Link>
        <Link to="/login" className="btn-secondary text-sm px-4 py-2">
          Analyze your own
        </Link>
      </header>

      <main className="max-w-3xl mx-auto px-6 pb-20">
        <p className="label-eyebrow mb-2">Shared Portfolio Report</p>
        <h1 className="font-display text-3xl font-semibold mb-8">
          {username || snapshot.username}
        </h1>

        <div className="card p-6 flex items-center gap-6 mb-6">
          <ScoreDonut score={portfolioResult.portfolioScore} />
          <div>
            <p className="text-xs text-grow font-mono mb-1">
              {portfolioResult.skillLevel}
            </p>
            <p className="text-sm text-ink-soft leading-relaxed">
              {portfolioResult.summary}
            </p>
          </div>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-8">
          <div className="card p-5">
            <p className="label-eyebrow mb-3">Strengths</p>
            {portfolioResult.strengths.map((s, i) => (
              <p key={i} className="text-xs mb-1.5 flex items-start gap-2">
                <span className="text-grow">✓</span> {s}
              </p>
            ))}
          </div>
          <div className="card p-5">
            <p className="label-eyebrow mb-3">Areas to improve</p>
            {portfolioResult.weaknesses.map((w, i) => (
              <p key={i} className="text-xs mb-1.5 flex items-start gap-2">
                <span className="text-flag">!</span> {w}
              </p>
            ))}
          </div>
        </div>

        {repos?.length > 0 && (
          <div>
            <p className="label-eyebrow mb-3">Repositories analyzed</p>
            <div className="space-y-2">
              {repos.map((r) => (
                <div
                  key={r.name}
                  className="card flex items-center justify-between px-4 py-3"
                >
                  <span className="font-mono text-sm">{r.name}</span>
                  <span className="font-mono text-xs px-2.5 py-1 rounded-full bg-violet-soft text-violet">
                    {r.qualityScore}/100
                  </span>
                </div>
              ))}
            </div>
          </div>
        )}

        <p className="text-center text-xs text-ink-faint mt-10">
          Generated by DevTrack — an AI career mentor for developers.
        </p>
      </main>
    </div>
  );
}
